2024-11-19 22:10:37,470 - ERROR - Error fetching https://q: HTTPSConnectionPool(host='q', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4339d8ebf0>: Failed to resolve 'q' ([Errno -2] Name or service not known)"))
2024-11-19 22:10:41,496 - ERROR - Error fetching https://q: HTTPSConnectionPool(host='q', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f4339d8f610>: Failed to resolve 'q' ([Errno -2] Name or service not known)"))
2024-11-19 22:11:57,462 - ERROR - Error fetching https://q: HTTPSConnectionPool(host='q', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe3354814e0>: Failed to resolve 'q' ([Errno -2] Name or service not known)"))
2024-11-19 22:12:01,515 - ERROR - Error fetching https://q: HTTPSConnectionPool(host='q', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe335481f00>: Failed to resolve 'q' ([Errno -2] Name or service not known)"))
